[package]
name = "sys"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "48c19604a1df93ac62a147e5ee708c150b459a69" }
async-trait = "0.1.50"
chrono = "0.4"
clap = "2.33"
itertools = "0.10.0"
pickledb = "0.4"
reqwest = "0.11"
rust_decimal = "^1.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-clap-utils = "=1.7.0"
solana-cli-config = "=1.7.0"
solana-cli-output = "=1.7.0"
solana-client = "=1.7.0"
solana-logger = "=1.7.0"
solana-remote-wallet = "=1.7.0"
solana-sdk = "=1.7.0"
solana-transaction-status = "=1.7.0"
solana-stake-program = "=1.7.0"
solana-vote-program = "=1.7.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tokio-binance = "1.0"

[profile.dev]
split-debuginfo = "unpacked"
