[package]
name = "sys"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
async-trait = "0.1.50"
bincode = "1.3.3"
chrono = "0.4"
chrono-humanize = "0.2.1"
clap = "2.33"
console = "0.14.1"
fd-lock = "3.0.0"
#ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "85de35236b456eba427fb7b666cc555645c2c6ba" }
ftx = { git = "https://github.com/mvines/ftx", rev = "600052e6a270bdaeee8f6767ae8f93fc45f83e69" }
#ftx = { path = "../ftx" }
itertools = "0.10.0"
separator = "0.4.1"
pickledb = "0.4"
reqwest = "0.11"
rust_decimal = "^1.13.0"
simple_excel_writer = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-clap-utils = "=1.8.11"
solana-cli-config = "=1.8.11"
solana-cli-output = "=1.8.11"
solana-client = "=1.8.11"
solana-logger = "=1.8.11"
solana-remote-wallet = "=1.8.11"
solana-sdk = "=1.8.11"
solana-stake-program = "=1.8.11"
solana-transaction-status = "=1.8.11"
solana-vote-program = "=1.8.11"
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
strum = { version = "0.23", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tokio-binance = "1.0"

[profile.dev]
split-debuginfo = "unpacked"
