[package]
name = "sys"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
async-trait = "0.1.50"
bincode = "1.3.3"
chrono = "0.4"
chrono-humanize = "0.2.1"
clap = "2.33"
console = "0.14.1"
fd-lock = "3.0.0"
#ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "85de35236b456eba427fb7b666cc555645c2c6ba" }
ftx = { git = "https://github.com/mvines/ftx", rev = "d5e6f4367dfbabd574859ca19a2f047d5eadad5b" }
#ftx = { path = "../ftx" }
itertools = "0.10.0"
separator = "0.4.1"
pickledb = "0.4"
reqwest = "0.11"
rust_decimal = "^1.13.0"
simple_excel_writer = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-clap-utils = "=1.7.14"
solana-cli-config = "=1.7.14"
solana-cli-output = "=1.7.14"
solana-client = "=1.7.14"
solana-logger = "=1.7.14"
solana-remote-wallet = "=1.7.14"
solana-sdk = "=1.7.14"
solana-stake-program = "=1.7.14"
solana-transaction-status = "=1.7.14"
solana-vote-program = "=1.7.14"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tokio-binance = "1.0"

[profile.dev]
split-debuginfo = "unpacked"
